junit_tests(
    sources = ["*.java"],
    runtime_platform = "java11",
    strict_deps = True,
    tags = ["bazel-compatible"],
    dependencies = [
        "3rdparty/jvm/org/scalatestplus:junit",
        "stitch/stitch-core",
        "util/util-core:scala",
    ],
)
