scala_library(
    sources = [
        "*.scala",
    ],
    strict_deps = True,
    tags = ["bazel-compatible"],
    dependencies = [
        "3rdparty/jvm/org/scalatest",
        "stitch/stitch-core",
        "util/util-core:scala",
        "util/util-core/src/main/scala/com/twitter/conversions",
    ],
)
